image:
  # x-release-please-start-version
  lfaiAPITag: 0.8.0
  # x-release-please-end
  kiwigridTag: 1.23.3

supabase:
  url: "https://supabase-kong.###ZARF_VAR_HOSTED_DOMAIN###"

api:
  replicas: 1
  port: 8080
  exposeOpenAPISchema: false

package:
  host: leapfrogai-api
